# Generated by Django 3.0.6 on 2020-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='jpy_deposit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='usd_deposit',
            field=models.FloatField(),
        ),
    ]
