# Generated by Django 3.0.6 on 2020-05-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200521_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('jpy_deposit', models.FloatField()),
                ('usd_deposit', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
