# Generated by Django 3.0.6 on 2020-05-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ave', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
    ]
