# Generated by Django 3.0.6 on 2020-05-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('fee', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('inbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbank', to='stock.Bank')),
                ('outbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbank', to='stock.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.User')),
            ],
        ),
    ]
