# Generated by Django 3.0.6 on 2020-05-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_bankdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='jpy_deposit',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='usd_deposit',
        ),
    ]
