# Generated by Django 3.0.6 on 2020-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20200530_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_trade',
            name='currency',
            field=models.IntegerField(choices=[(1, 'JPY'), (2, 'USD')], default=0, max_length=2),
        ),
    ]
