# Generated by Django 3.0.6 on 2020-05-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_bank_trade_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_trade',
            name='currency',
            field=models.IntegerField(choices=[(1, 'JPY'), (2, 'USD')], default=0),
        ),
    ]
