# Generated by Django 3.0.6 on 2020-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20200530_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_trade',
            name='currency',
            field=models.IntegerField(),
        ),
    ]
