# Generated by Django 3.0.6 on 2020-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20200530_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_trade',
            name='currency',
            field=models.IntegerField(choices=[(1, 'JPY'), (2, 'USD')], default=0),
        ),
    ]
