# Generated by Django 3.0.6 on 2020-05-31 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20200530_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_CompanyDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpy_deposit', models.FloatField()),
                ('usd_deposit', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('stock_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock_Company')),
            ],
        ),
    ]
