# Generated by Django 3.0.6 on 2020-05-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stockprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
