# Generated by Django 3.0.6 on 2020-06-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_remove_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('tax', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('h_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.H_Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.User')),
            ],
        ),
    ]
