# Generated by Django 3.0.6 on 2020-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_stock_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_trade',
            name='trade',
            field=models.IntegerField(choices=[(1, 'BUY'), (2, 'SELL')], default=0),
        ),
    ]
