# Generated by Django 3.0.6 on 2020-06-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_h_stock_stock_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.IntegerField(choices=[(1, 'JAPAN'), (2, 'USA')], default=0),
        ),
    ]
