# Generated by Django 3.0.6 on 2020-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_stock_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='real',
            field=models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], default=0),
        ),
    ]
