# Generated by Django 3.0.6 on 2020-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_bank_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_company',
            name='real',
            field=models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], default=0),
        ),
    ]
